"""Fix table name mismatch

Revision ID: 1aff3c5774ce
Revises: 66b606581afa
Create Date: 2025-11-19 19:13:17.031213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1aff3c5774ce'
down_revision = '66b606581afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_plans_date', table_name='daily_plans')
    op.drop_index('ix_daily_plans_id', table_name='daily_plans')
    op.drop_table('daily_plans')
    op.alter_column('daily_study_plans', 'recommended_tasks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('daily_study_plans', 'total_estimated_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_study_plans', 'total_tasks_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_study_plans', 'total_tasks_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_study_plans', 'total_estimated_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_study_plans', 'recommended_tasks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_table('daily_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actual_minutes_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('effectiveness_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skip_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_plans_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='daily_plans_pkey')
    )
    op.create_index('ix_daily_plans_id', 'daily_plans', ['id'], unique=False)
    op.create_index('ix_daily_plans_date', 'daily_plans', ['date'], unique=False)
    # ### end Alembic commands ###
