"""add_source_recommendation_ids_to_daily_plans

Revision ID: 5e2d9bf5d30f
Revises: 2025111102
Create Date: 2025-11-16 16:47:43.501051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e2d9bf5d30f'
down_revision = '2025111102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adaptive_recommendations', 'type',
               existing_type=postgresql.ENUM('review_flashcard', 'study_topic', 'take_quiz', 'read_document', 'focus_weak_area', 'reinforce_strength', name='recommendationtype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('adaptive_recommendations', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='recommendationpriority'),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('daily_study_plans', sa.Column('source_recommendation_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_study_plans', 'source_recommendation_ids')
    op.alter_column('adaptive_recommendations', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='recommendationpriority'),
               existing_nullable=True)
    op.alter_column('adaptive_recommendations', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('review_flashcard', 'study_topic', 'take_quiz', 'read_document', 'focus_weak_area', 'reinforce_strength', name='recommendationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
