"""allow nullable password for oauth users

Revision ID: 87de4ed7d545
Revises: be7d8616f78a
Create Date: 2025-10-02 19:57:25.000233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87de4ed7d545'
down_revision = 'be7d8616f78a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_owner_created', table_name='documents', if_exists=True)
    op.drop_index('idx_documents_processed_at', table_name='documents', if_exists=True)
    op.drop_index('idx_flashcards_next_review', table_name='flashcards', if_exists=True)
    op.drop_index('idx_flashcards_owner_document', table_name='flashcards', if_exists=True)
    op.drop_index('idx_quiz_attempts_user_completed', table_name='quiz_attempts', if_exists=True)
    op.drop_index('idx_quiz_questions_quiz_order', table_name='quiz_questions', if_exists=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_users_is_oauth_account', table_name='users', if_exists=True)
    op.drop_index('ix_users_oauth_email', table_name='users', if_exists=True)
    op.drop_index('ix_users_oauth_id', table_name='users', if_exists=True)
    op.drop_index('ix_users_oauth_provider', table_name='users', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_oauth_provider', 'users', ['oauth_provider'], unique=False)
    op.create_index('ix_users_oauth_id', 'users', ['oauth_id'], unique=False)
    op.create_index('ix_users_oauth_email', 'users', ['oauth_email'], unique=False)
    op.create_index('ix_users_is_oauth_account', 'users', ['is_oauth_account'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('idx_quiz_questions_quiz_order', 'quiz_questions', ['quiz_id', 'order_index'], unique=False)
    op.create_index('idx_quiz_attempts_user_completed', 'quiz_attempts', ['user_id', 'completed_at'], unique=False)
    op.create_index('idx_flashcards_owner_document', 'flashcards', ['owner_id', 'document_id'], unique=False)
    op.create_index('idx_flashcards_next_review', 'flashcards', ['owner_id', 'next_review_date'], unique=False)
    op.create_index('idx_documents_processed_at', 'documents', ['processed_at'], unique=False)
    op.create_index('idx_documents_owner_created', 'documents', ['owner_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
