from typing import Optional, Dict, Any, List
from datetime import date, datetime
from decimal import Decimal
from pydantic import BaseModel, Field, field_validator


# Task schema (for recommended_tasks JSON)
class RecommendedTask(BaseModel):
    """Individual recommended task"""
    type: str = Field(..., description="Task type: flashcard_review, quiz, document_reading, etc.")
    entity_ids: Optional[List[int]] = Field(None, description="List of entity IDs (for flashcards)")
    entity_id: Optional[int] = Field(None, description="Single entity ID (for quiz, document)")
    count: Optional[int] = Field(None, description="Number of items (e.g., 15 flashcards)")
    title: Optional[str] = Field(None, description="Task title")
    estimated_minutes: int = Field(..., ge=1, description="Estimated time in minutes")
    priority: str = Field(default="normal", description="Priority: low, normal, high, critical")
    reason: Optional[str] = Field(None, description="Why this task is recommended")
    topic: Optional[str] = Field(None, description="Topic/category")
    difficulty: Optional[str] = Field(None, description="Difficulty level")
    
    @field_validator('type')
    @classmethod
    def validate_type(cls, v):
        allowed = ['flashcard_review', 'quiz', 'document_reading', 'vocabulary_practice', 
                   'grammar_exercise', 'free_practice']
        if v not in allowed:
            raise ValueError(f"type must be one of {allowed}")
        return v


# Base schema
class DailyStudyPlanBase(BaseModel):
    plan_date: date = Field(..., description="Date of the plan")
    plan_summary: Optional[str] = Field(None, description="AI-generated summary")
    recommended_tasks: List[RecommendedTask] = Field(..., min_length=1, description="List of recommended tasks")
    total_estimated_minutes: int = Field(..., ge=1, description="Total estimated time")
    priority_level: str = Field(default="normal", description="Overall priority")
    difficulty_level: str = Field(default="medium", description="Overall difficulty")
    
    @field_validator('priority_level')
    @classmethod
    def validate_priority(cls, v):
        allowed = ['low', 'normal', 'high', 'critical']
        if v not in allowed:
            raise ValueError(f"priority_level must be one of {allowed}")
        return v
    
    @field_validator('difficulty_level')
    @classmethod
    def validate_difficulty(cls, v):
        allowed = ['easy', 'medium', 'hard']
        if v not in allowed:
            raise ValueError(f"difficulty_level must be one of {allowed}")
        return v


# Create schema (generated by AI)
class DailyStudyPlanCreate(DailyStudyPlanBase):
    """Schema for creating a daily study plan (usually AI-generated)"""
    schedule_id: Optional[int] = None


# Update schema (user marks completion, adds notes)
class DailyStudyPlanUpdate(BaseModel):
    """Schema for updating plan progress"""
    actual_minutes_spent: Optional[int] = Field(None, ge=0)
    completed_tasks_count: Optional[int] = Field(None, ge=0)
    actual_performance: Optional[Dict[str, Any]] = None
    status: Optional[str] = None
    skip_reason: Optional[str] = None
    effectiveness_rating: Optional[int] = Field(None, ge=1, le=5)
    user_notes: Optional[str] = None
    
    @field_validator('status')
    @classmethod
    def validate_status(cls, v):
        if v is not None:
            allowed = ['pending', 'in_progress', 'completed', 'partially_completed', 'skipped']
            if v not in allowed:
                raise ValueError(f"status must be one of {allowed}")
        return v


# Mark plan as started
class DailyStudyPlanStart(BaseModel):
    """Schema for marking plan as started"""
    pass


# Mark plan as completed
class DailyStudyPlanComplete(BaseModel):
    """Schema for marking plan as completed"""
    actual_minutes_spent: int = Field(..., ge=0)
    completed_tasks_count: int = Field(..., ge=0)
    actual_performance: Optional[Dict[str, Any]] = None
    effectiveness_rating: Optional[int] = Field(None, ge=1, le=5)
    user_notes: Optional[str] = None


# Response schema
class DailyStudyPlanResponse(DailyStudyPlanBase):
    """Schema for daily plan API response"""
    id: int
    user_id: int
    schedule_id: Optional[int] = None
    actual_minutes_spent: int
    is_completed: bool
    completion_percentage: Decimal
    completed_tasks_count: int
    total_tasks_count: int
    actual_performance: Optional[Dict[str, Any]] = None
    status: str
    skip_reason: Optional[str] = None
    ai_feedback: Optional[str] = None
    effectiveness_rating: Optional[int] = None
    user_notes: Optional[str] = None
    created_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    updated_at: datetime
    
    model_config = {"from_attributes": True}


# Today's plan response (special endpoint)
class TodayPlanResponse(BaseModel):
    """Response for GET /plans/today"""
    plan: Optional[DailyStudyPlanResponse] = None
    has_plan: bool
    is_new: bool  # Was just generated
    message: str
    
    # Additional context
    user_streak: Optional[int] = None
    total_study_time_this_week: Optional[int] = None
    goals_progress: Optional[List[Dict[str, Any]]] = None

