"""Add daily_plan_id, schedule_id, source_type, action_url to notifications

Revision ID: 20251120001
Revises: 0a66f0527ed1
Create Date: 2025-11-20 13:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20251120001"
down_revision = "0a66f0527ed1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications", sa.Column("daily_plan_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "notifications", sa.Column("schedule_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "notifications",
        sa.Column("source_type", sa.String(), server_default="system", nullable=True),
    )
    op.add_column("notifications", sa.Column("action_url", sa.String(), nullable=True))

    # Create indexes for better query performance
    op.create_index(
        "idx_notifications_daily_plan_id", "notifications", ["daily_plan_id", "user_id"]
    )
    op.create_index(
        "idx_notifications_schedule_id", "notifications", ["schedule_id", "user_id"]
    )
    op.create_index(
        "idx_notifications_source_type",
        "notifications",
        ["user_id", "source_type", "created_at"],
    )

    # Create foreign keys
    op.create_foreign_key(
        "fk_notifications_daily_plan_id",
        "notifications",
        "daily_study_plans",
        ["daily_plan_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_notifications_schedule_id",
        "notifications",
        "study_schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_notifications_schedule_id", "notifications")
    op.drop_constraint("fk_notifications_daily_plan_id", "notifications")

    op.drop_index("idx_notifications_source_type", "notifications")
    op.drop_index("idx_notifications_schedule_id", "notifications")
    op.drop_index("idx_notifications_daily_plan_id", "notifications")

    op.drop_column("notifications", "action_url")
    op.drop_column("notifications", "source_type")
    op.drop_column("notifications", "schedule_id")
    op.drop_column("notifications", "daily_plan_id")
    # ### end Alembic commands ###
