import { Link } from 'react-router-dom'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { BookOpen, Brain, Target, TrendingUp, Zap, Users } from 'lucide-react'

export default function LandingPage() {
  const features = [
    {
      icon: Zap,
      title: 'AI-Powered Content Generation',
      description: 'Upload documents and get instant quizzes, flashcards, and summaries generated by AI.'
    },
    {
      icon: Target,
      title: 'Personalized Learning Paths',
      description: 'Tailored study plans for IELTS, TOEIC, Business English, or general improvement.'
    },
    {
      icon: Brain,
      title: 'Smart Spaced Repetition',
      description: 'Optimized flashcard reviews that adapt to your learning progress and memory.'
    },
    {
      icon: TrendingUp,
      title: 'Progress Tracking',
      description: 'Comprehensive analytics to monitor your vocabulary growth and quiz performance.'
    },
    {
      icon: Users,
      title: 'Interactive Learning',
      description: 'AI chatbot for explanations, grammar help, and instant feedback on your answers.'
    },
    {
      icon: BookOpen,
      title: 'Multiple File Formats',
      description: 'Support for PDF, Word documents, and plain text - making any content learnable.'
    }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <header className="container mx-auto px-6 py-8">
        <nav className="flex justify-between items-center">
          <div className="flex items-center space-x-2">
            <BookOpen className="h-8 w-8 text-blue-600" />
            <span className="text-2xl font-bold text-gray-900">AI Learning Material</span>
          </div>
          <div className="space-x-4">
            <Button variant="ghost" asChild>
              <Link to="/login">Login</Link>
            </Button>
            <Button asChild>
              <Link to="/register">Get Started</Link>
            </Button>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-20 text-center">
        <h1 className="text-5xl font-bold text-gray-900 mb-6">
          Transform Any Document into
          <span className="text-blue-600"> Interactive Learning</span>
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
          Upload your English documents and let AI create personalized quizzes, flashcards, and study materials. 
          Perfect for IELTS, TOEIC, and professional English improvement.
        </p>
        <div className="space-x-4">
          <Button size="lg" asChild>
            <Link to="/register">Start Learning Free</Link>
          </Button>
          <Button size="lg" variant="outline">
            Watch Demo
          </Button>
        </div>
      </section>

      {/* Features Grid */}
      <section className="container mx-auto px-6 py-20">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Everything You Need to Master English
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Our AI-powered platform transforms your learning materials into engaging, 
            personalized study experiences.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <Card key={index} className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="flex items-center space-x-3">
                  <div className="p-2 bg-blue-100 rounded-lg">
                    <feature.icon className="h-6 w-6 text-blue-600" />
                  </div>
                  <CardTitle className="text-lg">{feature.title}</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-base">
                  {feature.description}
                </CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-blue-600 text-white py-20">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Revolutionize Your Learning?</h2>
          <p className="text-xl mb-8 opacity-90">
            Join thousands of learners who are already improving their English with AI
          </p>
          <Button size="lg" variant="secondary" asChild>
            <Link to="/register">Get Started Today</Link>
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-6 text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <BookOpen className="h-6 w-6" />
            <span className="text-lg font-semibold">AI Learning Material</span>
          </div>
          <p className="text-gray-400">
            Transform your English learning journey with AI-powered study materials
          </p>
        </div>
      </footer>
    </div>
  )
}
